language: go

go:
  - tip

install:
  - go get github.com/gorilla/mux
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega

script:
  - ginkgo -r --randomizeAllSpecs -cover
